// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf4nu6ZbcGttT6O3vNgTdPDIEvXJLZx3I',
    appId: '1:64775474395:web:839fdd1f1a19fa49cb50fe',
    messagingSenderId: '64775474395',
    projectId: 'uwbb-7e623',
    authDomain: 'uwbb-7e623.firebaseapp.com',
    storageBucket: 'uwbb-7e623.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzXTmEUrYq4z3rYF_hX6IGE7w3pVZms6U',
    appId: '1:64775474395:android:6fa5f36f6ed9f951cb50fe',
    messagingSenderId: '64775474395',
    projectId: 'uwbb-7e623',
    storageBucket: 'uwbb-7e623.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpp37OnvCCmrt9dMV1xipPrNPpu-dE3W8',
    appId: '1:64775474395:ios:b5206e9dc38d813ccb50fe',
    messagingSenderId: '64775474395',
    projectId: 'uwbb-7e623',
    storageBucket: 'uwbb-7e623.firebasestorage.app',
    iosBundleId: 'com.example.chabotUwb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpp37OnvCCmrt9dMV1xipPrNPpu-dE3W8',
    appId: '1:64775474395:ios:b5206e9dc38d813ccb50fe',
    messagingSenderId: '64775474395',
    projectId: 'uwbb-7e623',
    storageBucket: 'uwbb-7e623.firebasestorage.app',
    iosBundleId: 'com.example.chabotUwb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5nVevmr7kVL3YticSeP4gAfc3H3kSjYs',
    appId: '1:64775474395:web:01dc4af042bfc7e2cb50fe',
    messagingSenderId: '64775474395',
    projectId: 'uwbb-7e623',
    authDomain: 'uwbb-7e623.firebaseapp.com',
    storageBucket: 'uwbb-7e623.firebasestorage.app',
  );
}
